import { Wbs } from "@/types/Wbs";
import { NextApiRequest, NextApiResponse } from "next";

export default function handler(
  req: NextApiRequest,
  res: NextApiResponse<Wbs[]>
) {
  const mockData = [
    {
      id: 1,
      projectId: "PROJ001",
      projectName: "ウェブサイトリニューアル",
      wbsId: "D2-0001",
      phase: "基本設計",
      activity: "基本設計書",
      task: "基本設計書A作成",
      kinoSbt: "機能A",
      subsystem: "フロントエンド",
      tanto: "山田太郎",
      tantoRev: "鈴木花子",
      kijunStartDate: "2024-10-01",
      kijunEndDate: "2024-10-02",
      kijunKosu: 40,
      kijunKosuBuffer: 8,
      yoteiStartDate: "2024-10-01",
      yoteiEndDate: "2024-10-03",
      yoteiKosu: 40,
      jissekiStartDate: "2024-10-02",
      jissekiEndDate: null,
      jissekiKosu: 20,
      status: "完了",
      progress_Rate: 50,
    },
    {
      id: 2,
      projectId: "PROJ001",
      projectName: "ウェブサイトリニューアル",
      wbsId: "D2-0002",
      phase: "基本設計",
      activity: "基本設計書",
      task: "基本設計書B作成",
      kinoSbt: "機能A",
      subsystem: "フロントエンド",
      tanto: "山田太郎",
      tantoRev: "鈴木花子",
      kijunStartDate: "2024-10-03",
      kijunEndDate: "2024-10-03",
      kijunKosu: 40,
      kijunKosuBuffer: 8,
      yoteiStartDate: "2024-10-03",
      yoteiEndDate: "2024-10-03",
      yoteiKosu: 40,
      jissekiStartDate: "2024-10-03",
      jissekiEndDate: null,
      jissekiKosu: 20,
      status: "完了",
      progress_Rate: 120,
    },
    {
      id: 3,
      projectId: "PROJ001",
      projectName: "ウェブサイトリニューアル",
      wbsId: "D2-0003",
      phase: "基本設計",
      activity: "基本設計",
      task: "基本設計書C作成",
      kinoSbt: "機能B",
      subsystem: "フロントエンド",
      tanto: "佐藤次郎",
      tantoRev: "高橋美咲",
      kijunStartDate: "2024-10-05",
      kijunEndDate: "2024-10-08",
      kijunKosu: 80,
      kijunKosuBuffer: 16,
      yoteiStartDate: "2024-10-05",
      yoteiEndDate: "2024-10-08",
      yoteiKosu: 80,
      jissekiStartDate: null,
      jissekiEndDate: null,
      jissekiKosu: 200,
      status: "完了",
      progress_Rate: 0,
    },
    {
      id: 4,
      projectId: "PROJ001",
      projectName: "ウェブサイトリニューアル",
      wbsId: "D3-0001",
      phase: "開発",
      activity: "コーディング",
      task: "A機能実装",
      kinoSbt: "機能A",
      subsystem: "バックエンド",
      tanto: "田中三郎",
      tantoRev: "伊藤恵子",
      kijunStartDate: "2024-10-11",
      kijunEndDate: "2024-10-20",
      kijunKosu: 100,
      kijunKosuBuffer: 20,
      yoteiStartDate: "2024-10-11",
      yoteiEndDate: "2024-10-20",
      yoteiKosu: 100,
      jissekiStartDate: null,
      jissekiEndDate: null,
      jissekiKosu: 0,
      status: "未着手",
      progress_Rate: 0,
    },
    {
      id: 5,
      projectId: "PROJ001",
      projectName: "ウェブサイトリニューアル",
      wbsId: "D3-0002",
      phase: "開発",
      activity: "コーディング",
      task: "B機能実装",
      kinoSbt: "機能A",
      subsystem: "バックエンド",
      tanto: "田中三郎",
      tantoRev: "伊藤恵子",
      kijunStartDate: "2024-10-21",
      kijunEndDate: "2024-10-25",
      kijunKosu: 100,
      kijunKosuBuffer: 20,
      yoteiStartDate: "2024-10-21",
      yoteiEndDate: "2024-10-25",
      yoteiKosu: 100,
      jissekiStartDate: null,
      jissekiEndDate: null,
      jissekiKosu: 0,
      status: "未着手",
      progress_Rate: 0,
    },
    {
      id: 6,
      projectId: "PROJ001",
      projectName: "ウェブサイトリニューアル",
      wbsId: "D3-0003",
      phase: "開発",
      activity: "コーディング",
      task: "C機能実装",
      kinoSbt: "機能A",
      subsystem: "バックエンド",
      tanto: "田中三郎",
      tantoRev: "伊藤恵子",
      kijunStartDate: "2024-10-22",
      kijunEndDate: "2024-10-25",
      kijunKosu: 100,
      kijunKosuBuffer: 20,
      yoteiStartDate: "2024-10-22",
      yoteiEndDate: "2024-10-25",
      yoteiKosu: 100,
      jissekiStartDate: null,
      jissekiEndDate: null,
      jissekiKosu: 0,
      status: null,
      progress_Rate: 0,
    },
    {
      id: 7,
      projectId: "PROJ001",
      projectName: "ウェブサイトリニューアル",
      wbsId: "D2-0004",
      phase: "基本設計",
      activity: "基本設計",
      task: "レビュー",
      kinoSbt: "機能B",
      subsystem: "フロントエンド",
      tanto: "佐藤次郎",
      tantoRev: "高橋美咲",
      kijunStartDate: "2024-10-01",
      kijunEndDate: "2024-10-31",
      kijunKosu: 80,
      kijunKosuBuffer: 16,
      yoteiStartDate: "2024-10-05",
      yoteiEndDate: "2024-10-08",
      yoteiKosu: 80,
      jissekiStartDate: null,
      jissekiEndDate: null,
      jissekiKosu: 200,
      status: "完了",
      progress_Rate: 0,
    },
  ];

  switch (req.method) {
    case "GET":
      res.status(200).json(mockData)
      break;
    default:
      res.setHeader("Allow", ["GET"]);
      res.status(405).end(`Method ${req.method} Not Allowed`);
  }
}
